// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package whirlpool

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// IncreaseLiquidityV2 is the `increaseLiquidityV2` instruction.
type IncreaseLiquidityV2 struct {
	LiquidityAmount       *ag_binary.Uint128
	TokenMaxA             *uint64
	TokenMaxB             *uint64
	RemainingAccountsInfo *RemainingAccountsInfo `bin:"optional"`

	// [0] = [WRITE] whirlpool
	//
	// [1] = [] tokenProgramA
	//
	// [2] = [] tokenProgramB
	//
	// [3] = [] memoProgram
	//
	// [4] = [SIGNER] positionAuthority
	//
	// [5] = [WRITE] position
	//
	// [6] = [] positionTokenAccount
	//
	// [7] = [] tokenMintA
	//
	// [8] = [] tokenMintB
	//
	// [9] = [WRITE] tokenOwnerAccountA
	//
	// [10] = [WRITE] tokenOwnerAccountB
	//
	// [11] = [WRITE] tokenVaultA
	//
	// [12] = [WRITE] tokenVaultB
	//
	// [13] = [WRITE] tickArrayLower
	//
	// [14] = [WRITE] tickArrayUpper
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewIncreaseLiquidityV2InstructionBuilder creates a new `IncreaseLiquidityV2` instruction builder.
func NewIncreaseLiquidityV2InstructionBuilder() *IncreaseLiquidityV2 {
	nd := &IncreaseLiquidityV2{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 15),
	}
	return nd
}

// SetLiquidityAmount sets the "liquidityAmount" parameter.
func (inst *IncreaseLiquidityV2) SetLiquidityAmount(liquidityAmount ag_binary.Uint128) *IncreaseLiquidityV2 {
	inst.LiquidityAmount = &liquidityAmount
	return inst
}

// SetTokenMaxA sets the "tokenMaxA" parameter.
func (inst *IncreaseLiquidityV2) SetTokenMaxA(tokenMaxA uint64) *IncreaseLiquidityV2 {
	inst.TokenMaxA = &tokenMaxA
	return inst
}

// SetTokenMaxB sets the "tokenMaxB" parameter.
func (inst *IncreaseLiquidityV2) SetTokenMaxB(tokenMaxB uint64) *IncreaseLiquidityV2 {
	inst.TokenMaxB = &tokenMaxB
	return inst
}

// SetRemainingAccountsInfo sets the "remainingAccountsInfo" parameter.
func (inst *IncreaseLiquidityV2) SetRemainingAccountsInfo(remainingAccountsInfo RemainingAccountsInfo) *IncreaseLiquidityV2 {
	inst.RemainingAccountsInfo = &remainingAccountsInfo
	return inst
}

// SetWhirlpoolAccount sets the "whirlpool" account.
func (inst *IncreaseLiquidityV2) SetWhirlpoolAccount(whirlpool ag_solanago.PublicKey) *IncreaseLiquidityV2 {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(whirlpool).WRITE()
	return inst
}

// GetWhirlpoolAccount gets the "whirlpool" account.
func (inst *IncreaseLiquidityV2) GetWhirlpoolAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetTokenProgramAAccount sets the "tokenProgramA" account.
func (inst *IncreaseLiquidityV2) SetTokenProgramAAccount(tokenProgramA ag_solanago.PublicKey) *IncreaseLiquidityV2 {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(tokenProgramA)
	return inst
}

// GetTokenProgramAAccount gets the "tokenProgramA" account.
func (inst *IncreaseLiquidityV2) GetTokenProgramAAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetTokenProgramBAccount sets the "tokenProgramB" account.
func (inst *IncreaseLiquidityV2) SetTokenProgramBAccount(tokenProgramB ag_solanago.PublicKey) *IncreaseLiquidityV2 {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(tokenProgramB)
	return inst
}

// GetTokenProgramBAccount gets the "tokenProgramB" account.
func (inst *IncreaseLiquidityV2) GetTokenProgramBAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetMemoProgramAccount sets the "memoProgram" account.
func (inst *IncreaseLiquidityV2) SetMemoProgramAccount(memoProgram ag_solanago.PublicKey) *IncreaseLiquidityV2 {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(memoProgram)
	return inst
}

// GetMemoProgramAccount gets the "memoProgram" account.
func (inst *IncreaseLiquidityV2) GetMemoProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetPositionAuthorityAccount sets the "positionAuthority" account.
func (inst *IncreaseLiquidityV2) SetPositionAuthorityAccount(positionAuthority ag_solanago.PublicKey) *IncreaseLiquidityV2 {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(positionAuthority).SIGNER()
	return inst
}

// GetPositionAuthorityAccount gets the "positionAuthority" account.
func (inst *IncreaseLiquidityV2) GetPositionAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetPositionAccount sets the "position" account.
func (inst *IncreaseLiquidityV2) SetPositionAccount(position ag_solanago.PublicKey) *IncreaseLiquidityV2 {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(position).WRITE()
	return inst
}

// GetPositionAccount gets the "position" account.
func (inst *IncreaseLiquidityV2) GetPositionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetPositionTokenAccountAccount sets the "positionTokenAccount" account.
func (inst *IncreaseLiquidityV2) SetPositionTokenAccountAccount(positionTokenAccount ag_solanago.PublicKey) *IncreaseLiquidityV2 {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(positionTokenAccount)
	return inst
}

// GetPositionTokenAccountAccount gets the "positionTokenAccount" account.
func (inst *IncreaseLiquidityV2) GetPositionTokenAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetTokenMintAAccount sets the "tokenMintA" account.
func (inst *IncreaseLiquidityV2) SetTokenMintAAccount(tokenMintA ag_solanago.PublicKey) *IncreaseLiquidityV2 {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(tokenMintA)
	return inst
}

// GetTokenMintAAccount gets the "tokenMintA" account.
func (inst *IncreaseLiquidityV2) GetTokenMintAAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetTokenMintBAccount sets the "tokenMintB" account.
func (inst *IncreaseLiquidityV2) SetTokenMintBAccount(tokenMintB ag_solanago.PublicKey) *IncreaseLiquidityV2 {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(tokenMintB)
	return inst
}

// GetTokenMintBAccount gets the "tokenMintB" account.
func (inst *IncreaseLiquidityV2) GetTokenMintBAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetTokenOwnerAccountAAccount sets the "tokenOwnerAccountA" account.
func (inst *IncreaseLiquidityV2) SetTokenOwnerAccountAAccount(tokenOwnerAccountA ag_solanago.PublicKey) *IncreaseLiquidityV2 {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(tokenOwnerAccountA).WRITE()
	return inst
}

// GetTokenOwnerAccountAAccount gets the "tokenOwnerAccountA" account.
func (inst *IncreaseLiquidityV2) GetTokenOwnerAccountAAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetTokenOwnerAccountBAccount sets the "tokenOwnerAccountB" account.
func (inst *IncreaseLiquidityV2) SetTokenOwnerAccountBAccount(tokenOwnerAccountB ag_solanago.PublicKey) *IncreaseLiquidityV2 {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(tokenOwnerAccountB).WRITE()
	return inst
}

// GetTokenOwnerAccountBAccount gets the "tokenOwnerAccountB" account.
func (inst *IncreaseLiquidityV2) GetTokenOwnerAccountBAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetTokenVaultAAccount sets the "tokenVaultA" account.
func (inst *IncreaseLiquidityV2) SetTokenVaultAAccount(tokenVaultA ag_solanago.PublicKey) *IncreaseLiquidityV2 {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(tokenVaultA).WRITE()
	return inst
}

// GetTokenVaultAAccount gets the "tokenVaultA" account.
func (inst *IncreaseLiquidityV2) GetTokenVaultAAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetTokenVaultBAccount sets the "tokenVaultB" account.
func (inst *IncreaseLiquidityV2) SetTokenVaultBAccount(tokenVaultB ag_solanago.PublicKey) *IncreaseLiquidityV2 {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(tokenVaultB).WRITE()
	return inst
}

// GetTokenVaultBAccount gets the "tokenVaultB" account.
func (inst *IncreaseLiquidityV2) GetTokenVaultBAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

// SetTickArrayLowerAccount sets the "tickArrayLower" account.
func (inst *IncreaseLiquidityV2) SetTickArrayLowerAccount(tickArrayLower ag_solanago.PublicKey) *IncreaseLiquidityV2 {
	inst.AccountMetaSlice[13] = ag_solanago.Meta(tickArrayLower).WRITE()
	return inst
}

// GetTickArrayLowerAccount gets the "tickArrayLower" account.
func (inst *IncreaseLiquidityV2) GetTickArrayLowerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(13)
}

// SetTickArrayUpperAccount sets the "tickArrayUpper" account.
func (inst *IncreaseLiquidityV2) SetTickArrayUpperAccount(tickArrayUpper ag_solanago.PublicKey) *IncreaseLiquidityV2 {
	inst.AccountMetaSlice[14] = ag_solanago.Meta(tickArrayUpper).WRITE()
	return inst
}

// GetTickArrayUpperAccount gets the "tickArrayUpper" account.
func (inst *IncreaseLiquidityV2) GetTickArrayUpperAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(14)
}

func (inst IncreaseLiquidityV2) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_IncreaseLiquidityV2,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst IncreaseLiquidityV2) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *IncreaseLiquidityV2) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.LiquidityAmount == nil {
			return errors.New("LiquidityAmount parameter is not set")
		}
		if inst.TokenMaxA == nil {
			return errors.New("TokenMaxA parameter is not set")
		}
		if inst.TokenMaxB == nil {
			return errors.New("TokenMaxB parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Whirlpool is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.TokenProgramA is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.TokenProgramB is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.MemoProgram is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.PositionAuthority is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.Position is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.PositionTokenAccount is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.TokenMintA is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.TokenMintB is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.TokenOwnerAccountA is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.TokenOwnerAccountB is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.TokenVaultA is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.TokenVaultB is not set")
		}
		if inst.AccountMetaSlice[13] == nil {
			return errors.New("accounts.TickArrayLower is not set")
		}
		if inst.AccountMetaSlice[14] == nil {
			return errors.New("accounts.TickArrayUpper is not set")
		}
	}
	return nil
}

func (inst *IncreaseLiquidityV2) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("IncreaseLiquidityV2")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=4]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("      LiquidityAmount", *inst.LiquidityAmount))
						paramsBranch.Child(ag_format.Param("            TokenMaxA", *inst.TokenMaxA))
						paramsBranch.Child(ag_format.Param("            TokenMaxB", *inst.TokenMaxB))
						paramsBranch.Child(ag_format.Param("RemainingAccountsInfo (OPT)", inst.RemainingAccountsInfo))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=15]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("         whirlpool", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("     tokenProgramA", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("     tokenProgramB", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("       memoProgram", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta(" positionAuthority", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("          position", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("     positionToken", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("        tokenMintA", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("        tokenMintB", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("tokenOwnerAccountA", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("tokenOwnerAccountB", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("       tokenVaultA", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("       tokenVaultB", inst.AccountMetaSlice.Get(12)))
						accountsBranch.Child(ag_format.Meta("    tickArrayLower", inst.AccountMetaSlice.Get(13)))
						accountsBranch.Child(ag_format.Meta("    tickArrayUpper", inst.AccountMetaSlice.Get(14)))
					})
				})
		})
}

func (obj IncreaseLiquidityV2) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `LiquidityAmount` param:
	err = encoder.Encode(obj.LiquidityAmount)
	if err != nil {
		return err
	}
	// Serialize `TokenMaxA` param:
	err = encoder.Encode(obj.TokenMaxA)
	if err != nil {
		return err
	}
	// Serialize `TokenMaxB` param:
	err = encoder.Encode(obj.TokenMaxB)
	if err != nil {
		return err
	}
	// Serialize `RemainingAccountsInfo` param (optional):
	{
		if obj.RemainingAccountsInfo == nil {
			err = encoder.WriteBool(false)
			if err != nil {
				return err
			}
		} else {
			err = encoder.WriteBool(true)
			if err != nil {
				return err
			}
			err = encoder.Encode(obj.RemainingAccountsInfo)
			if err != nil {
				return err
			}
		}
	}
	return nil
}
func (obj *IncreaseLiquidityV2) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `LiquidityAmount`:
	err = decoder.Decode(&obj.LiquidityAmount)
	if err != nil {
		return err
	}
	// Deserialize `TokenMaxA`:
	err = decoder.Decode(&obj.TokenMaxA)
	if err != nil {
		return err
	}
	// Deserialize `TokenMaxB`:
	err = decoder.Decode(&obj.TokenMaxB)
	if err != nil {
		return err
	}
	// Deserialize `RemainingAccountsInfo` (optional):
	{
		ok, err := decoder.ReadBool()
		if err != nil {
			return err
		}
		if ok {
			err = decoder.Decode(&obj.RemainingAccountsInfo)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// NewIncreaseLiquidityV2Instruction declares a new IncreaseLiquidityV2 instruction with the provided parameters and accounts.
func NewIncreaseLiquidityV2Instruction(
	// Parameters:
	liquidityAmount ag_binary.Uint128,
	tokenMaxA uint64,
	tokenMaxB uint64,
	remainingAccountsInfo RemainingAccountsInfo,
	// Accounts:
	whirlpool ag_solanago.PublicKey,
	tokenProgramA ag_solanago.PublicKey,
	tokenProgramB ag_solanago.PublicKey,
	memoProgram ag_solanago.PublicKey,
	positionAuthority ag_solanago.PublicKey,
	position ag_solanago.PublicKey,
	positionTokenAccount ag_solanago.PublicKey,
	tokenMintA ag_solanago.PublicKey,
	tokenMintB ag_solanago.PublicKey,
	tokenOwnerAccountA ag_solanago.PublicKey,
	tokenOwnerAccountB ag_solanago.PublicKey,
	tokenVaultA ag_solanago.PublicKey,
	tokenVaultB ag_solanago.PublicKey,
	tickArrayLower ag_solanago.PublicKey,
	tickArrayUpper ag_solanago.PublicKey) *IncreaseLiquidityV2 {
	return NewIncreaseLiquidityV2InstructionBuilder().
		SetLiquidityAmount(liquidityAmount).
		SetTokenMaxA(tokenMaxA).
		SetTokenMaxB(tokenMaxB).
		SetRemainingAccountsInfo(remainingAccountsInfo).
		SetWhirlpoolAccount(whirlpool).
		SetTokenProgramAAccount(tokenProgramA).
		SetTokenProgramBAccount(tokenProgramB).
		SetMemoProgramAccount(memoProgram).
		SetPositionAuthorityAccount(positionAuthority).
		SetPositionAccount(position).
		SetPositionTokenAccountAccount(positionTokenAccount).
		SetTokenMintAAccount(tokenMintA).
		SetTokenMintBAccount(tokenMintB).
		SetTokenOwnerAccountAAccount(tokenOwnerAccountA).
		SetTokenOwnerAccountBAccount(tokenOwnerAccountB).
		SetTokenVaultAAccount(tokenVaultA).
		SetTokenVaultBAccount(tokenVaultB).
		SetTickArrayLowerAccount(tickArrayLower).
		SetTickArrayUpperAccount(tickArrayUpper)
}
