// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package whirlpool

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// SetDefaultProtocolFeeRate is the `setDefaultProtocolFeeRate` instruction.
type SetDefaultProtocolFeeRate struct {
	DefaultProtocolFeeRate *uint16

	// [0] = [WRITE] whirlpoolsConfig
	//
	// [1] = [SIGNER] feeAuthority
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewSetDefaultProtocolFeeRateInstructionBuilder creates a new `SetDefaultProtocolFeeRate` instruction builder.
func NewSetDefaultProtocolFeeRateInstructionBuilder() *SetDefaultProtocolFeeRate {
	nd := &SetDefaultProtocolFeeRate{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetDefaultProtocolFeeRate sets the "defaultProtocolFeeRate" parameter.
func (inst *SetDefaultProtocolFeeRate) SetDefaultProtocolFeeRate(defaultProtocolFeeRate uint16) *SetDefaultProtocolFeeRate {
	inst.DefaultProtocolFeeRate = &defaultProtocolFeeRate
	return inst
}

// SetWhirlpoolsConfigAccount sets the "whirlpoolsConfig" account.
func (inst *SetDefaultProtocolFeeRate) SetWhirlpoolsConfigAccount(whirlpoolsConfig ag_solanago.PublicKey) *SetDefaultProtocolFeeRate {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(whirlpoolsConfig).WRITE()
	return inst
}

// GetWhirlpoolsConfigAccount gets the "whirlpoolsConfig" account.
func (inst *SetDefaultProtocolFeeRate) GetWhirlpoolsConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetFeeAuthorityAccount sets the "feeAuthority" account.
func (inst *SetDefaultProtocolFeeRate) SetFeeAuthorityAccount(feeAuthority ag_solanago.PublicKey) *SetDefaultProtocolFeeRate {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(feeAuthority).SIGNER()
	return inst
}

// GetFeeAuthorityAccount gets the "feeAuthority" account.
func (inst *SetDefaultProtocolFeeRate) GetFeeAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

func (inst SetDefaultProtocolFeeRate) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_SetDefaultProtocolFeeRate,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst SetDefaultProtocolFeeRate) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *SetDefaultProtocolFeeRate) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.DefaultProtocolFeeRate == nil {
			return errors.New("DefaultProtocolFeeRate parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.WhirlpoolsConfig is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.FeeAuthority is not set")
		}
	}
	return nil
}

func (inst *SetDefaultProtocolFeeRate) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("SetDefaultProtocolFeeRate")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("DefaultProtocolFeeRate", *inst.DefaultProtocolFeeRate))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("whirlpoolsConfig", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("    feeAuthority", inst.AccountMetaSlice.Get(1)))
					})
				})
		})
}

func (obj SetDefaultProtocolFeeRate) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `DefaultProtocolFeeRate` param:
	err = encoder.Encode(obj.DefaultProtocolFeeRate)
	if err != nil {
		return err
	}
	return nil
}
func (obj *SetDefaultProtocolFeeRate) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `DefaultProtocolFeeRate`:
	err = decoder.Decode(&obj.DefaultProtocolFeeRate)
	if err != nil {
		return err
	}
	return nil
}

// NewSetDefaultProtocolFeeRateInstruction declares a new SetDefaultProtocolFeeRate instruction with the provided parameters and accounts.
func NewSetDefaultProtocolFeeRateInstruction(
	// Parameters:
	defaultProtocolFeeRate uint16,
	// Accounts:
	whirlpoolsConfig ag_solanago.PublicKey,
	feeAuthority ag_solanago.PublicKey) *SetDefaultProtocolFeeRate {
	return NewSetDefaultProtocolFeeRateInstructionBuilder().
		SetDefaultProtocolFeeRate(defaultProtocolFeeRate).
		SetWhirlpoolsConfigAccount(whirlpoolsConfig).
		SetFeeAuthorityAccount(feeAuthority)
}
