// This code was AUTOGENERATED using the library.
// Please DO NOT EDIT THIS FILE.

package cpi_guard

import binary "github.com/gagliardetto/binary"

// CpiGuard Struct
type CpiGuard struct {
	// Lock privileged token operations from happening via CPI
	LockCpi bool
}

const CPI_GUARD_SIZE = 1

func (obj *CpiGuard) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	if err = encoder.Encode(&obj.LockCpi); err != nil {
		return err
	}
	return nil
}

func (obj *CpiGuard) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	if err = decoder.Decode(&obj.LockCpi); err != nil {
		return err
	}
	return nil
}
