// This code was AUTOGENERATED using the library.
// Please DO NOT EDIT THIS FILE.

package cpi_guard

import (
	"errors"

	binary "github.com/gagliardetto/binary"
	"github.com/gagliardetto/solana-go/programs/common"
	format "github.com/gagliardetto/solana-go/text/format"
	treeout "github.com/gagliardetto/treeout"
)

// Enable Instruction
type Enable struct {
	// [0] = [WRITE] account `The account to update.`
	// [1] = [SIGNER] owner `The account's owner.`
	common.AccountMetaSlice `bin:"-"`
	_programId              *common.PublicKey
}

// NewEnableInstructionBuilder creates a new `Enable` instruction builder.
func NewEnableInstructionBuilder() *Enable {
	return &Enable{
		AccountMetaSlice: make(common.AccountMetaSlice, 2),
	}
}

// NewEnableInstruction
//
// Parameters:
//
//	account: The account to update.
//	owner: The account's owner.
func NewEnableInstruction(
	account common.PublicKey,
	owner common.PublicKey,
) *Enable {
	return NewEnableInstructionBuilder().
		SetAccountAccount(account).
		SetOwnerAccount(owner)
}

// SetAccountAccount sets the "account" parameter.
// The account to update.
func (obj *Enable) SetAccountAccount(account common.PublicKey) *Enable {
	obj.AccountMetaSlice[0] = common.Meta(account).WRITE()
	return obj
}

// GetAccountAccount gets the "account" parameter.
// The account to update.
func (obj *Enable) GetAccountAccount() *common.AccountMeta {
	return obj.AccountMetaSlice.Get(0)
}

// SetOwnerAccount sets the "owner" parameter.
// The account's owner.
func (obj *Enable) SetOwnerAccount(owner common.PublicKey, multiSigners ...common.PublicKey) *Enable {
	if len(multiSigners) > 0 {
		obj.AccountMetaSlice[1] = common.Meta(owner)
		for _, value := range multiSigners {
			obj.AccountMetaSlice.Append(common.NewAccountMeta(value, false, true))
		}
	} else {
		obj.AccountMetaSlice[1] = common.Meta(owner).SIGNER()
	}
	return obj
}

// GetOwnerAccount gets the "owner" parameter.
// The account's owner.
func (obj *Enable) GetOwnerAccount() *common.AccountMeta {
	return obj.AccountMetaSlice.Get(1)
}

func (obj *Enable) SetProgramId(programId *common.PublicKey) *Enable {
	obj._programId = programId
	return obj
}

func (obj *Enable) Build() *Instruction {
	return &Instruction{
		BaseVariant: binary.BaseVariant{
			Impl:   obj,
			TypeID: binary.TypeIDFromBytes([]byte{Instruction_Enable}),
		},
		programId: obj._programId,
		typeIdLen: 1,
	}
}

func (obj *Enable) Validate() error {

	if obj.AccountMetaSlice[0] == nil {
		return errors.New("[Enable] accounts.account is not set")
	}
	if obj.AccountMetaSlice[1] == nil {
		return errors.New("[Enable] accounts.owner is not set")
	}
	return nil
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (obj *Enable) ValidateAndBuild() (*Instruction, error) {
	if err := obj.Validate(); err != nil {
		return nil, err
	}
	return obj.Build(), nil
}

func (obj *Enable) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	return nil
}

func (obj *Enable) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	return nil
}

func (obj *Enable) EncodeToTree(parent treeout.Branches) {
	parent.Child(format.Program(ProgramName, common.As(ProgramID))).
		ParentFunc(func(programBranch treeout.Branches) {
			programBranch.Child(format.Instruction("Enable")).
				ParentFunc(func(instructionBranch treeout.Branches) {
					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch treeout.Branches) {})
					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch treeout.Branches) {
						accountsBranch.Child(common.FormatMeta("account", obj.AccountMetaSlice.Get(0)))
						accountsBranch.Child(common.FormatMeta("  owner", obj.AccountMetaSlice.Get(1)))
					})
				})
		})
}

// Disable Instruction
type Disable struct {
	// [0] = [WRITE] account `The account to update.`
	// [1] = [SIGNER] owner `The account's owner.`
	common.AccountMetaSlice `bin:"-"`
	_programId              *common.PublicKey
}

// NewDisableInstructionBuilder creates a new `Disable` instruction builder.
func NewDisableInstructionBuilder() *Disable {
	return &Disable{
		AccountMetaSlice: make(common.AccountMetaSlice, 2),
	}
}

// NewDisableInstruction
//
// Parameters:
//
//	account: The account to update.
//	owner: The account's owner.
func NewDisableInstruction(
	account common.PublicKey,
	owner common.PublicKey,
) *Disable {
	return NewDisableInstructionBuilder().
		SetAccountAccount(account).
		SetOwnerAccount(owner)
}

// SetAccountAccount sets the "account" parameter.
// The account to update.
func (obj *Disable) SetAccountAccount(account common.PublicKey) *Disable {
	obj.AccountMetaSlice[0] = common.Meta(account).WRITE()
	return obj
}

// GetAccountAccount gets the "account" parameter.
// The account to update.
func (obj *Disable) GetAccountAccount() *common.AccountMeta {
	return obj.AccountMetaSlice.Get(0)
}

// SetOwnerAccount sets the "owner" parameter.
// The account's owner.
func (obj *Disable) SetOwnerAccount(owner common.PublicKey, multiSigners ...common.PublicKey) *Disable {
	if len(multiSigners) > 0 {
		obj.AccountMetaSlice[1] = common.Meta(owner)
		for _, value := range multiSigners {
			obj.AccountMetaSlice.Append(common.NewAccountMeta(value, false, true))
		}
	} else {
		obj.AccountMetaSlice[1] = common.Meta(owner).SIGNER()
	}
	return obj
}

// GetOwnerAccount gets the "owner" parameter.
// The account's owner.
func (obj *Disable) GetOwnerAccount() *common.AccountMeta {
	return obj.AccountMetaSlice.Get(1)
}

func (obj *Disable) SetProgramId(programId *common.PublicKey) *Disable {
	obj._programId = programId
	return obj
}

func (obj *Disable) Build() *Instruction {
	return &Instruction{
		BaseVariant: binary.BaseVariant{
			Impl:   obj,
			TypeID: binary.TypeIDFromBytes([]byte{Instruction_Disable}),
		},
		programId: obj._programId,
		typeIdLen: 1,
	}
}

func (obj *Disable) Validate() error {

	if obj.AccountMetaSlice[0] == nil {
		return errors.New("[Disable] accounts.account is not set")
	}
	if obj.AccountMetaSlice[1] == nil {
		return errors.New("[Disable] accounts.owner is not set")
	}
	return nil
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (obj *Disable) ValidateAndBuild() (*Instruction, error) {
	if err := obj.Validate(); err != nil {
		return nil, err
	}
	return obj.Build(), nil
}

func (obj *Disable) MarshalWithEncoder(encoder *binary.Encoder) (err error) {
	return nil
}

func (obj *Disable) UnmarshalWithDecoder(decoder *binary.Decoder) (err error) {
	return nil
}

func (obj *Disable) EncodeToTree(parent treeout.Branches) {
	parent.Child(format.Program(ProgramName, common.As(ProgramID))).
		ParentFunc(func(programBranch treeout.Branches) {
			programBranch.Child(format.Instruction("Disable")).
				ParentFunc(func(instructionBranch treeout.Branches) {
					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch treeout.Branches) {})
					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch treeout.Branches) {
						accountsBranch.Child(common.FormatMeta("account", obj.AccountMetaSlice.Get(0)))
						accountsBranch.Child(common.FormatMeta("  owner", obj.AccountMetaSlice.Get(1)))
					})
				})
		})
}
