// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package associated_token_account

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// CreateIdempotent is the `create_idempotent` instruction.
type CreateIdempotent struct {

	// [0] = [WRITE, SIGNER] payer
	//
	// [1] = [WRITE] associated_token_account
	//
	// [2] = [] wallet
	//
	// [3] = [] mint
	//
	// [4] = [] system_program
	//
	// [5] = [] token_program
	//
	// [6] = [] sysvar_rent
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewCreateIdempotentInstructionBuilder creates a new `CreateIdempotent` instruction builder.
func NewCreateIdempotentInstructionBuilder() *CreateIdempotent {
	nd := &CreateIdempotent{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 7),
	}
	return nd
}

// SetPayerAccount sets the "payer" account.
func (inst *CreateIdempotent) SetPayerAccount(payer ag_solanago.PublicKey) *CreateIdempotent {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(payer).WRITE().SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
func (inst *CreateIdempotent) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetAssociatedTokenAccount sets the "associated_token_account" account.
func (inst *CreateIdempotent) SetAssociatedTokenAccount(associatedTokenAccount ag_solanago.PublicKey) *CreateIdempotent {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(associatedTokenAccount).WRITE()
	return inst
}

// GetAssociatedTokenAccount gets the "associated_token_account" account.
func (inst *CreateIdempotent) GetAssociatedTokenAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetWalletAccount sets the "wallet" account.
func (inst *CreateIdempotent) SetWalletAccount(wallet ag_solanago.PublicKey) *CreateIdempotent {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(wallet)
	return inst
}

// GetWalletAccount gets the "wallet" account.
func (inst *CreateIdempotent) GetWalletAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetMintAccount sets the "mint" account.
func (inst *CreateIdempotent) SetMintAccount(mint ag_solanago.PublicKey) *CreateIdempotent {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(mint)
	return inst
}

// GetMintAccount gets the "mint" account.
func (inst *CreateIdempotent) GetMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetSystemProgramAccount sets the "system_program" account.
func (inst *CreateIdempotent) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *CreateIdempotent {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "system_program" account.
func (inst *CreateIdempotent) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetTokenProgramAccount sets the "token_program" account.
func (inst *CreateIdempotent) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *CreateIdempotent {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "token_program" account.
func (inst *CreateIdempotent) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetSysvarRentAccount sets the "sysvar_rent" account.
func (inst *CreateIdempotent) SetSysvarRentAccount(sysvarRent ag_solanago.PublicKey) *CreateIdempotent {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(sysvarRent)
	return inst
}

// GetSysvarRentAccount gets the "sysvar_rent" account.
func (inst *CreateIdempotent) GetSysvarRentAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

func (inst CreateIdempotent) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: ag_binary.TypeIDFromUint8(Instruction_CreateIdempotent),
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst CreateIdempotent) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *CreateIdempotent) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Payer is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.AssociatedTokenAccount is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Wallet is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Mint is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.SysvarRent is not set")
		}
	}
	return nil
}

func (inst *CreateIdempotent) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("CreateIdempotent")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=7]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("            payer", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("associated_token_", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("           wallet", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("             mint", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("   system_program", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("    token_program", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("      sysvar_rent", inst.AccountMetaSlice.Get(6)))
					})
				})
		})
}

func (obj CreateIdempotent) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *CreateIdempotent) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewCreateIdempotentInstruction declares a new CreateIdempotent instruction with the provided parameters and accounts.
func NewCreateIdempotentInstruction(
	// Accounts:
	payer ag_solanago.PublicKey,
	associatedTokenAccount ag_solanago.PublicKey,
	wallet ag_solanago.PublicKey,
	mint ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	sysvarRent ag_solanago.PublicKey) *CreateIdempotent {
	return NewCreateIdempotentInstructionBuilder().
		SetPayerAccount(payer).
		SetAssociatedTokenAccount(associatedTokenAccount).
		SetWalletAccount(wallet).
		SetMintAccount(mint).
		SetSystemProgramAccount(systemProgram).
		SetTokenProgramAccount(tokenProgram).
		SetSysvarRentAccount(sysvarRent)
}


func NewCreateIdempotentInstructionWithDerivation(
// Accounts:
	payer ag_solanago.PublicKey,
	wallet ag_solanago.PublicKey,
	mint ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey) *CreateIdempotent {
	associatedTokenAccount, _, _ := ag_solanago.FindAssociatedTokenAddress(
		wallet,
		mint,
		tokenProgram,
	)
	return NewCreateIdempotentInstructionBuilder().
		SetPayerAccount(payer).
		SetAssociatedTokenAccount(associatedTokenAccount).
		SetWalletAccount(wallet).
		SetMintAccount(mint).
		SetSystemProgramAccount(ag_solanago.SystemProgramID).
		SetTokenProgramAccount(tokenProgram).
		SetSysvarRentAccount(ag_solanago.SysVarRentPubkey)
}
