[package]
name = "parity"
version = "0.0.0"
edition = "2021"

[dependencies]
solana-zk-elgamal-proof-interface = "=0.1.3"
solana-address = "=2.5.0"
solana-instruction = { version = "=3.0.0", default-features = false, features = ["std"] }
solana-pubkey = "=3.0.0"
solana-zk-sdk = "4"
spl-token-2022-interface = "=2.1.0"
spl-token-confidential-transfer-proof-extraction = "0.5"
bytemuck = "1.25.0"
num-traits = "0.2"
