// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package raydium_clmm

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Update rewards info of the given pool, can be called for everyone
//
// # Arguments
//
// * `ctx`- The context of accounts
//
type UpdateRewardInfos struct {

	// [0] = [WRITE] poolState
	// ··········· The liquidity pool for which reward info to update
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewUpdateRewardInfosInstructionBuilder creates a new `UpdateRewardInfos` instruction builder.
func NewUpdateRewardInfosInstructionBuilder() *UpdateRewardInfos {
	nd := &UpdateRewardInfos{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 1),
	}
	return nd
}

// SetPoolStateAccount sets the "poolState" account.
// The liquidity pool for which reward info to update
func (inst *UpdateRewardInfos) SetPoolStateAccount(poolState ag_solanago.PublicKey) *UpdateRewardInfos {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(poolState).WRITE()
	return inst
}

// GetPoolStateAccount gets the "poolState" account.
// The liquidity pool for which reward info to update
func (inst *UpdateRewardInfos) GetPoolStateAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

func (inst UpdateRewardInfos) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_UpdateRewardInfos,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst UpdateRewardInfos) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *UpdateRewardInfos) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.PoolState is not set")
		}
	}
	return nil
}

func (inst *UpdateRewardInfos) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("UpdateRewardInfos")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=1]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("poolState", inst.AccountMetaSlice.Get(0)))
					})
				})
		})
}

func (obj UpdateRewardInfos) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *UpdateRewardInfos) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewUpdateRewardInfosInstruction declares a new UpdateRewardInfos instruction with the provided parameters and accounts.
func NewUpdateRewardInfosInstruction(
	// Accounts:
	poolState ag_solanago.PublicKey) *UpdateRewardInfos {
	return NewUpdateRewardInfosInstructionBuilder().
		SetPoolStateAccount(poolState)
}
